### ISSUE TITLE
PHP Warning in SimpleFileFetcher.php on line 16 for non existing files

### ISSUE THREAD

**Issue by kghbln** [JeroenDeDauw/FileFetcher#2]
Wolfgangs [GitHub template](https://www.semantic-mediawiki.org/wiki/Template:Github) on smw.o causes this to pop up via the cron runs of "runJobs.php"

```
PHP Warning:  file_get_contents(https://cdn.rawgit.com/SemanticMediaWiki/SemanticMediaWiki/master/issues/1343): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
 in /.../w/vendor/jeroen/file-fetcher/src/SimpleFileFetcher.php on line 16
```

**Comment by JeroenDeDauw** [comment]
This should not cause a PHP warning, so that's a bug. However note that the GitHub extension is for pulling in files part of the git repo. It cannot pull in GitHub issues.

**Comment by kghbln** [comment]
He is using it [to link an not to embed](https://www.semantic-mediawiki.org/wiki/Technical_documentation_todo) in this particular case.

**Comment by kghbln** [comment]
Are recent stack trace with xdebug:

```
PHP Warning:  file_get_contents(https://cdn.rawgit.com/SemanticMediaWiki/SemanticMediaWiki/master/issues/902): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
 in /.../w/vendor/jeroen/file-fetcher/src/SimpleFileFetcher.php on line 16
PHP Stack trace:
PHP   1. {main}() /.../w/extensions/SemanticMediaWiki/maintenance/rebuildData.php:0
PHP   2. require_once() /.../w/extensions/SemanticMediaWiki/maintenance/rebuildData.php:197
PHP   3. SMW\Maintenance\RebuildData->execute() /.../w/maintenance/doMaintenance.php:103
PHP   4. SMW\Maintenance\DataRebuilder->rebuild() /.../w/extensions/SemanticMediaWiki/maintenance/rebuildData.php:149
PHP   5. SMW\Maintenance\DataRebuilder->doRebuildAll() /.../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php:167
PHP   6. SMW\Maintenance\DataRebuilder->doExecuteFor() /.../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php:266
PHP   7. SMW\SQLStore\ByIdDataRebuildDispatcher->dispatchRebuildFor() /.../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php:307
PHP   8. SMW\MediaWiki\Jobs\UpdateJob->run() /.../w/extensions/SemanticMediaWiki/src/SQLStore/ByIdDataRebuildDispatcher.php:191
PHP   9. SMW\MediaWiki\Jobs\UpdateJob->doUpdate() /.../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php:56
PHP  10. SMW\MediaWiki\Jobs\UpdateJob->doPrepareForUpdate() /.../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php:87
PHP  11. SMW\MediaWiki\Jobs\UpdateJob->needToParsePageContentBeforeUpdate() /.../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php:118
PHP  12. SMW\ContentParser->parse() /.../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php:135
PHP  13. SMW\ContentParser->fetchFromParser() /.../w/extensions/SemanticMediaWiki/includes/ContentParser.php:147
PHP  14. Parser->parse() /.../w/extensions/SemanticMediaWiki/includes/ContentParser.php:202
PHP  15. Parser->internalParse() /.../w/includes/parser/Parser.php:435
PHP  16. Parser->replaceVariables() /.../w/includes/parser/Parser.php:1232
PHP  17. PPFrame_DOM->expand() /.../w/includes/parser/Parser.php:3334
PHP  18. Parser->braceSubstitution() /.../w/includes/parser/Preprocessor_DOM.php:1169
PHP  19. PPFrame_DOM->expand() /.../w/includes/parser/Parser.php:3659
PHP  20. Parser->braceSubstitution() /.../w/includes/parser/Preprocessor_DOM.php:1169
PHP  21. Parser->callParserFunction() /.../w/includes/parser/Parser.php:3517
PHP  22. call_user_func_array:{/.../w/includes/parser/Parser.php:3783}() /.../w/includes/parser/Parser.php:3783
PHP  23. ExtParserFunctions::ifObj() /.../w/includes/parser/Parser.php:3783
PHP  24. PPFrame_DOM->expand() /.../w/extensions/ParserFunctions/ParserFunctions_body.php:106
PHP  25. Parser->braceSubstitution() /.../w/includes/parser/Preprocessor_DOM.php:1169
PHP  26. Parser->callParserFunction() /.../w/includes/parser/Parser.php:3517
PHP  27. call_user_func_array:{/.../w/includes/parser/Parser.php:3783}() /.../w/includes/parser/Parser.php:3783
PHP  28. ExtParserFunctions::ifObj() /.../w/includes/parser/Parser.php:3783
PHP  29. PPFrame_DOM->expand() /.../w/extensions/ParserFunctions/ParserFunctions_body.php:106
PHP  30. Parser->braceSubstitution() /.../w/includes/parser/Preprocessor_DOM.php:1169
PHP  31. Parser->callParserFunction() /.../w/includes/parser/Parser.php:3517
PHP  32. call_user_func_array:{/.../w/includes/parser/Parser.php:3783}() /.../w/includes/parser/Parser.php:3783
PHP  33. ParserHooks\HookRegistrant->ParserHooks\{closure}() /.../w/includes/parser/Parser.php:3783
PHP  34. ParserHooks\FunctionRunner->run() /.../w/vendor/mediawiki/parser-hooks/src/HookRegistrant.php:45
PHP  35. GitHub\GitHubParserHook->handle() /.../w/vendor/mediawiki/parser-hooks/src/FunctionRunner.php:49
PHP  36. GitHub\GitHubParserHook->getRenderedContent() /.../w/vendor/jeroen/mediawiki-github/src/GitHubParserHook.php:36
PHP  37. GitHub\GitHubParserHook->getFileContent() /.../w/vendor/jeroen/mediawiki-github/src/GitHubParserHook.php:48
PHP  38. FileFetcher\CachingFileFetcher->fetchFile() /.../w/vendor/jeroen/mediawiki-github/src/GitHubParserHook.php:58
PHP  39. FileFetcher\CachingFileFetcher->retrieveAndCacheFile() /.../w/vendor/jeroen/file-fetcher/src/CachingFileFetcher.php:29
PHP  40. FileFetcher\SimpleFileFetcher->fetchFile() /.../w/vendor/jeroen/file-fetcher/src/CachingFileFetcher.php:36
PHP  41. file_get_contents() /.../w/vendor/jeroen/file-fetcher/src/SimpleFileFetcher.php:16
PHP Warning:  file_get_contents(https://cdn.rawgit.com/SemanticMediaWiki/SemanticMediaWiki/master/issues/874): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
 in /.../w/vendor/jeroen/file-fetcher/src/SimpleFileFetcher.php on line 16

```

**Comment by JeroenDeDauw** [comment]
Looks like this issue was actually fixed in 2015, and that SMW.org is using an older version of this library. Will create a new release of https://github.com/JeroenDeDauw/GitHub to fix that.

**Comment by kghbln** [comment]
@JeroenDeDauw The new version 1.0.3 is live on smw.o however the issue [still persists](https://www.semantic-mediawiki.org/wiki/Help:Sorting). Thus this issue needs to be reopened I'm afraid.

**Comment by kghbln** [comment]
@JeroenDeDauw Oops. Should have looked closer. Please disregard my previous post. There is actually now another issue. Will open an issue report.
